spring.application.name=mydelivery

spring.jpa.show-sql=true
server.port=8080
spring.datasource.url=jdbc:mysql://172.17.32.108/mydelivery
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.username=aluno
spring.datasource.password=12345678